version: '3.3'
services:
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'menus'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'goodreads'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'goodreads'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  app:
    image: volunteerapp
    depends_on:
      - mysqldb
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://127.0.0.1:3306/menus?useSSL=false",
            "spring.datasource.username" : "root",
            "spring.datasource.password" : "goodreads",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'
    ports:
      - 8080:8080
# Names our volume
volumes:
  my-db:
    driver: volunteerappdriver

